# Generated by Django 5.2.4 on 2025-08-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('science', 'Science'), ('history', 'History')], max_length=75)),
                ('IBSN', models.IntegerField()),
                ('publication_date', models.DateField()),
                ('average_rating', models.PositiveIntegerField()),
            ],
        ),
    ]
